---
title: "Census Geographies"
output:
  bookdown::html_document2:
    number_sections: true
    # toc: true
    # toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, 
                      dev = "png")

# Load packages ----
library(tidycensus)
library(tidyverse)
library(scales)
library(janitor)
library(rcartocolor)
library(RColorBrewer)
library("ggspatial")
library(tigris)
library(sf)
library(ggthemes) # theme_map()
library(patchwork)

# Tract geometries ----
alb_geo <- tracts(state = "VA", county = "003")
cville_geo <- tracts(state = "VA", county = "540")

alb_geo_2019 <- tracts(state = "VA", county = "003", year = 2019)
```

```{r, echo=FALSE, fig.width=9, fig.height=5, fig.cap=""}
# AHDI Charlottesville tracts, geospatial ----
ahdi_tract_cville <- read_csv("../data/ahdi_tract_cville.csv") %>% 
  mutate(GEOID = as.character(GEOID),
         ahdi = round(ahdi, digits = 1))
ahdi_tract_cville <- ahdi_tract_cville[order(ahdi_tract_cville$tractnames, decreasing=FALSE),]

ahdi_tract_cville <- ahdi_tract_cville %>%
  left_join(cville_geo, by = join_by(GEOID == GEOID), keep = TRUE) %>% 
  st_as_sf() %>% 
  arrange(GEOID.x)

ahdi_tract_cville$row_num <- 1:nrow(ahdi_tract_cville)
ahdi_tract_cville$legend_entry <- paste0(ahdi_tract_cville$row_num, " - ", ahdi_tract_cville$tractnames, " (",  ahdi_tract_cville$NAMELSAD, ")")

# Geospatial visualization
ahdi_cville_map <- ahdi_tract_cville %>%
  ggplot() +
  annotation_map_tile(zoomin = 1, progress = "none", cachedir = "../data/tempdata/") +
  geom_sf(color = "black", fill = NA, linewidth = 0.75) +
  geom_sf_text(aes(label = row_num), size = 5, color = "black", fontface = "bold", nudge_y = 0.001, nudge_x = 0.002) +
  # scale_fill_stepsn(colors = pal_ahdi,
  #                   # labels = scales::label_currency(scale = 1),
  #                   n.breaks = 6,
  #                   guide = guide_colourbar(title = "American HD Index",
  #                                           title.position = "top",
  #                                           direction = "horizontal",
  #                                           title.hjust = 0.5,
  #                                           # nbin = 6,
  #                                           theme = theme(legend.key.height  = unit(0.5, "lines"),
  #                                                         legend.key.width = unit(12, "lines"),
  #                                                         text = element_text(size = 11)) 
  #                                           )
  #                   )+
  theme_map()+
  # geom_text(aes(label=legend_entry, x=Inf, y=row_num, hjust=0)) +
  theme(
    # legend.position.inside=c(1, 1.06),
        # legend.justification="right",
        plot.title = element_text(size = 14),
        plot.subtitle = element_text(size = 14)
        # plot.margin = unit(c(1,15,1,1), "lines")
        )

# ahdi_cville_map
# Rank plot
cville_rank_data <- ahdi_tract_cville 
# %>% 
#   group_by(ahdi) %>% 
#   summarise(tractnames = paste(tractnames, collapse = "\n")) %>% 
#   na.exclude() 

names <- cville_rank_data$legend_entry
ahdi_label <- cville_rank_data$row_num

cville_ahdi_rank <-  ggplot(ahdi_tract_cville, aes(x = 0, y = row_num, label = names)) +
    geom_line(color = NA)+
    # geom_point(aes(color=as.factor(row_num)), size=5)+
    geom_text(label = names, hjust = 0, 
              # nudge_x = 0.005, 
              # nudge_y = 0.01,
              size = 4.5, 
              # angle=55, 
              lineheight = 0.8) +
   # scale_color_carto_d(name = "American HD Index: ",
   #                         type = "diverging", palette = "Purp", direction = 1) +
    scale_x_continuous(limits = c(0,.1),
                       expand = c(0, 0))+
  scale_y_reverse(breaks = ahdi_label,
                       labels = ahdi_label) +
    # scale_y_continuous(limits=rev,
    #                    breaks = ahdi_label,
    #                    labels = ahdi_label
    #                    ) +
  theme_minimal()+
    theme(axis.line.x = element_blank(),
          axis.ticks.x = element_blank(),
          axis.text.x = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          panel.grid.minor = element_blank(),
          panel.grid.major = element_blank(),
          axis.text.y = element_blank(),
          # axis.text.y = element_text(size = 11),
          axis.ticks = element_blank(),
          # axis.ticks = element_line(linewidth = .5),
          # axis.ticks.length.y = unit(.25, "cm"),
          plot.title.position= "plot",
          plot.caption.position = "plot",
          plot.caption = element_text(hjust = 0),
          legend.position="none")

# cville_ahdi_rank
  
  (ahdi_cville_map + cville_ahdi_rank) +
  plot_layout(widths = c(1, 1)) +
  plot_annotation(title = 'City of Charlottesville Census Tracts',
                  # subtitle = locality_name,
                  caption = "",
                  theme = theme(plot.title = element_text(size = 18),
                                plot.subtitle = element_text(size = 14)))

```

```{r, echo=FALSE, fig.width=12, fig.height=9.5, fig.cap=""}
# Albemarle tracts, geospatial ----
ahdi_tract_alb <- read_csv("../data/ahdi_tract_alb.csv") %>% 
  mutate(GEOID = as.character(GEOID),
         ahdi = round(ahdi, digits = 1))
ahdi_tract_alb <- ahdi_tract_alb[order(ahdi_tract_alb$tractnames, decreasing=FALSE),]

ahdi_tract_alb <- ahdi_tract_alb %>%
  left_join(alb_geo, by = join_by(GEOID == GEOID), keep = TRUE) %>% 
  st_as_sf() %>% 
  arrange(GEOID.x)

ahdi_tract_alb$row_num <- 1:nrow(ahdi_tract_alb)
ahdi_tract_alb$legend_entry <- paste0(ahdi_tract_alb$row_num, " - ", ahdi_tract_alb$tractnames, " (",  ahdi_tract_alb$NAMELSAD, ")")

# Geospatial visualization
ahdi_alb_map <- ahdi_tract_alb %>%
  ggplot() +
  annotation_map_tile(zoomin = 1, progress = "none", cachedir = "../data/tempdata/") +
  geom_sf(color = "black", fill = NA, linewidth = 0.5) +
  geom_sf_text(aes(label = row_num), size = 3.5, color = "black", fontface = "bold", 
               # nudge_y = 0.001, 
               # nudge_x = 0.002
               ) +
  theme_map()+
  theme(
        plot.title = element_text(size = 14),
        plot.subtitle = element_text(size = 14)
        )


# Rank plot
names <- ahdi_tract_alb$legend_entry
ahdi_label <- ahdi_tract_alb$row_num

alb_ahdi_rank <-  ggplot(ahdi_tract_alb, aes(x = 0, y = row_num, label = names)) +
    geom_line(color = NA)+
    geom_text(label = names, hjust = 0, 
              # nudge_x = 0.005, 
              # nudge_y = 0.01,
              size = 5 
              # angle=55, 
              # lineheight = 0.8
              ) +
    scale_x_continuous(limits = c(0,.1),
                       expand = c(0, 0))+
  scale_y_reverse(breaks = ahdi_label,
                       labels = ahdi_label) +
  theme_minimal()+
    theme(axis.line.x = element_blank(),
          axis.ticks.x = element_blank(),
          axis.text.x = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          panel.grid.minor = element_blank(),
          panel.grid.major = element_blank(),
          axis.text.y = element_blank(),
          # axis.text.y = element_text(size = 11),
          axis.ticks = element_blank(),
          # axis.ticks = element_line(linewidth = .5),
          # axis.ticks.length.y = unit(.25, "cm"),
          plot.title.position= "plot",
          plot.caption.position = "plot",
          plot.caption = element_text(hjust = 0),
          legend.position="none")


  (ahdi_alb_map + alb_ahdi_rank) +
  plot_layout(widths = c(1.5, 1)) +
  plot_annotation(title = 'Albemarle County Census Tracts (2020 and after)',
                  # subtitle = locality_name,
                  caption = "",
                  theme = theme(plot.title = element_text(size = 18),
                                plot.subtitle = element_text(size = 14)))

```

```{r, echo=FALSE, fig.width=12, fig.height=9.5, fig.cap=""}
ahdi_tract_2019 <- read_csv("../data/ahdi_tract_combined.csv") %>% 
  select(GEOID_TRACT_10,ahdi_2019, tractnames_2019, fullname_2019) %>% 
  mutate(GEOID_TRACT_10 = as.character(GEOID_TRACT_10),
         ahdi_2019 = round(ahdi_2019, digits = 1))
ahdi_tract_2019 <- ahdi_tract_2019[order(ahdi_tract_2019$tractnames_2019, decreasing=FALSE),]

ahdi_tract_2019 <- ahdi_tract_2019 %>%
  left_join(alb_geo_2019, by = join_by(GEOID_TRACT_10 == GEOID), keep = TRUE) %>% 
  st_as_sf() %>% 
  arrange(GEOID) %>% 
  unique()

ahdi_tract_2019$row_num <- 1:nrow(ahdi_tract_2019)
ahdi_tract_2019$legend_entry <- paste0(ahdi_tract_2019$row_num, " - ", ahdi_tract_2019$tractnames_2019, " (",  ahdi_tract_2019$NAMELSAD, ")")

# Geospatial visualization
ahdi_alb_map <- ahdi_tract_2019 %>%
  ggplot() +
  annotation_map_tile(zoomin = 1, progress = "none", cachedir = "../data/tempdata/") +
  geom_sf(color = "black", fill = NA, linewidth = 0.5) +
  geom_sf_text(aes(label = row_num), size = 3.5, color = "black", fontface = "bold", 
               # nudge_y = 0.001, 
               # nudge_x = 0.002
               ) +
  theme_map()+
  theme(
        plot.title = element_text(size = 14),
        plot.subtitle = element_text(size = 14)
        )


# Rank plot
names <- ahdi_tract_2019$legend_entry
ahdi_label <- ahdi_tract_2019$row_num

alb_ahdi_rank <-  ggplot(ahdi_tract_2019, aes(x = 0, y = row_num, label = names)) +
    geom_line(color = NA)+
    geom_text(label = names, hjust = 0, 
              # nudge_x = 0.005, 
              # nudge_y = 0.01,
              size = 5 
              # angle=55, 
              # lineheight = 0.8
              ) +
    scale_x_continuous(limits = c(0,.1),
                       expand = c(0, 0))+
  scale_y_reverse(breaks = ahdi_label,
                       labels = ahdi_label) +
  theme_minimal()+
    theme(axis.line.x = element_blank(),
          axis.ticks.x = element_blank(),
          axis.text.x = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          panel.grid.minor = element_blank(),
          panel.grid.major = element_blank(),
          axis.text.y = element_blank(),
          # axis.text.y = element_text(size = 11),
          axis.ticks = element_blank(),
          # axis.ticks = element_line(linewidth = .5),
          # axis.ticks.length.y = unit(.25, "cm"),
          plot.title.position= "plot",
          plot.caption.position = "plot",
          plot.caption = element_text(hjust = 0),
          legend.position="none")


  (ahdi_alb_map + alb_ahdi_rank) +
  plot_layout(widths = c(1.5, 1)) +
  plot_annotation(title = 'Albemarle County Census Tracts (2010-2020)',
                  # subtitle = locality_name,
                  caption = "",
                  theme = theme(plot.title = element_text(size = 18),
                                plot.subtitle = element_text(size = 14)))

```

