---
title: "Equity Profile Demographics - Albemarle"
output: html_document
---
```{css, echo=FALSE}
.main-container.container-fluid {
max-width: 1200px;
  margin-left: auto;
  margin-right: auto;
  padding: 0 4.167%;
}


```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidycensus)
library(tidyverse)
library(scales)
library(RColorBrewer)
library("ggspatial")
library(tigris)
library(ggrepel)
library(ggpubr)
library(readxl)
library(ggpol)
library(patchwork)


```

```{r, echo=FALSE, fig.width=8, fig.height=7}
# Race over time ----

# Region 1790-2020 ----
region_sheet <- read_excel("../data/regional_profile_raceovertime.xlsx", sheet = "regional_data")
region_1790_2020 <- region_sheet %>% select(!...7) %>% 
  rename("race_white" = "white",
         "race_nonwhite" = "nonwhite",
         "per_white" = "white_per",
         "per_nonwhite" = "nonwhite_per") %>%
  pivot_longer(cols = c(starts_with("race"), starts_with("per")),
               names_to = c('.value', 'label'),
               names_pattern = '(.*?)_(.*)') %>% 
  rename("total_pop" = "total",
         "estimate" = "race",
         "percent" = "per")

region_line <- region_1790_2020 %>% 
  mutate(text = paste0(round(percent, 0), "%"),
         pos = case_when(percent >= 50 ~ 1,
                         percent < 50 ~ -1
                         )) %>% 
  ggplot(aes(x = year, y = percent, color = label, label = text)) +
  geom_line(linewidth = 1) +
  geom_point() +
  geom_text(aes(y = (percent + sign(pos) *3)), size = 3, hjust = 0.4, show.legend = FALSE) +
  scale_x_continuous(breaks = seq(from = 1790, to = 2020, by = 10),
                     name = "") +
  scale_y_continuous(limits = c(0,100),
                     labels = label_percent(scale = 1),
                     name = "") +
    scale_color_manual(values = c("#3B8EA5", "#b2b8be")) +
  labs(color = "", title = "White and non-white populations in the Charlottesville-Albemarle Region, 1790-2020") +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "top",
        axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid.minor.x = element_blank())

region_line


```

```{r, echo=FALSE}

# Albemarle 1900-2020 ----
alb_sheet <- read_excel("../data/regional_profile_raceovertime.xlsx", sheet = "albemarle_data")
alb_1900_2020 <- alb_sheet %>% select(!...7) %>% 
  rename("race_white" = "white",
         "race_nonwhite" = "nonwhite",
         "per_white" = "white_per",
         "per_nonwhite" = "nonwhite_per") %>%
  pivot_longer(cols = c(starts_with("race"), starts_with("per")),
               names_to = c('.value', 'label'),
               names_pattern = '(.*?)_(.*)') %>% 
  rename("total_pop" = "total",
         "estimate" = "race",
         "percent" = "per")

alb_line <- alb_1900_2020 %>% 
  mutate(text = paste0(round(percent, 0), "%")) %>% 
  ggplot(aes(x = year, y = round(percent, 0), color = label, label = text)) +
  geom_line(linewidth = 1) +
  geom_point() +
    geom_text(size = 3, hjust=0.5, vjust=-1, color="black") +
  scale_x_continuous(breaks = seq(from = 1900, to = 2020, by = 10),
                     name = "") +
  scale_y_continuous(limits = c(0,100),
                     labels = label_percent(scale = 1),
                     name = "") +
  scale_color_manual(values = c("#3B8EA5", "#b2b8be")) +
  labs(color = "", title = "White and non-white populations in Albemarle, 1900-2020") +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "top",
        axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid.minor.x = element_blank())

alb_line


```


```{r, echo=FALSE}
# Ethnicity by Race, 2012-2022 ----

alb_ethn_race_2012_2022 <- read_csv("../data/alb_ethn_race_2012_2022.csv")
alb_ethn_race_2012_2022 <- alb_ethn_race_2012_2022 %>% 
  mutate(year = factor(year, levels = c("2012","2013","2014","2015","2016",
                                        "2017","2018","2019","2020","2021","2022")),
         label = factor(label, 
                        levels = c("Not Hispanic or Latino: White alone", "Not Hispanic or Latino: Black or African American alone", "Hispanic or Latino", "Not Hispanic or Latino: Two or more races", "Not Hispanic or Latino: Asian alone", "Not Hispanic or Latino: American Indian and Alaska Native alone", "Not Hispanic or Latino: Native Hawaiian and Other Pacific Islander alone", "Not Hispanic or Latino: Some other race alone"), 
                        labels = c("White", "Black", "Hispanic", "Multiracial",  "Asian", "American Indian/Alaskan Native", "Native Hawaiian/Pacific Islander", "Other Racial Identities")),
         percent_moe = round(100 * (moe / total_pop), digits = 2),
         text = case_when(percent >= 1 ~ paste0(round(percent, 0), "%"),
                          percent < 1 ~ "")
  )


# Stacked bar
alb_ethn_race_plot <- alb_ethn_race_2012_2022 %>% 
  ggplot(aes(x = year, y = percent, group = year, fill = label, 
             label = text)) +
  geom_bar(stat = "identity", width = 0.8) +
  geom_text(size = 3, position = position_stack(vjust = 0.5)) +
  scale_x_discrete(name = "") +
  scale_y_continuous(labels = label_percent(scale = 1),
                     name = "") +
  labs(color = "", title = "Albemarle: Race/Ethnic Composition, 2012-2022") +
  # scale_fill_manual(values = color_blind_pal) +
  # scale_fill_manual(values = c("#b2b8be", "#ff641e", "#009ddc", "#fbb12d", "#b4cd23", "#ee2b75", "#b69cfd", "#43daed")) +
  scale_fill_manual(values = c("#b2b8be", "#ff641e", "#b4cd23", "#ee2b75","#009ddc", "#fbb12d", "#b69cfd", "#43daed")) +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "top",
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank())

alb_ethn_race_plot



```
```{r, echo=FALSE, fig.height=7}
# Age Groups: 2012 and 2022 ----

# Albemarle (Age Groups), 2022

alb_age_2012_2022 <- read_csv("../data/alb_age_2012_2022.csv")
alb_age_2012_2022 <- alb_age_2012_2022 %>% 
  mutate(label = factor(label,
                        levels = c("Under 5 years", "5 to 9 years", "10 to 14 years", "15 to 19 years",
                                   "20 to 24 years", "25 to 34 years", "35 to 44 years", "45 to 54 years",
                                   "55 to 59 years", "60 to 64 years", "65 to 74 years", "75 to 84 years",
                                   "85 years and over")),
         percent = round(percent, 0))

alb_age_plot <- alb_age_2012_2022 %>% 
  # mutate(year = factor(year, levels = c("2022", "2012"))) %>%
  ggplot(aes(x = label, y = percent, fill = factor(year))) +  # Convert year to factor here
  geom_bar(stat = "identity", position = position_dodge2(width = 0.9, preserve = "single"), width = 0.8) +
  geom_text(aes(label = scales::percent(percent / 100, accuracy = 1)), 
            position = position_dodge2(width = 0.9, preserve = "single"), 
            vjust = 0.5,
            hjust = -0.2,
            size = 3) +
  scale_x_discrete(name = "") +
  scale_y_continuous(labels = scales::percent_format(scale = 1),
                     limits = c(0,30),
                     expand = expansion(mult = c(0, 0)),
                     name = "") +
  scale_fill_manual(values = c("#b2b8be", "#ff641e")) +  # Apply custom colors here
  coord_flip() +
  theme_minimal() +
  theme(legend.position = "top",
        panel.grid.minor.x = element_blank()) +
  # guides(fill = guide_legend(reverse = TRUE)) +
  labs(fill = "", title = "Age of Albemarle Residents, 2012 v. 2022")
  

alb_age_plot


```

```{r, echo=FALSE, fig.height=5, fig.width=8}
# Age Groups (Butterfly): 2012 and 2022 ----

age_plot_2012 <- alb_age_2012_2022 %>% 
  filter(year == 2012) %>% 
  ggplot(aes(y = label, x = percent, fill = factor(year))) +  # Convert year to factor here
  geom_bar(stat = "identity", position = position_dodge2(width = 0.9, preserve = "single"), width = 0.8) +
  geom_text(aes(label = scales::percent(percent / 100, accuracy = 1)), 
            position = position_dodge2(width = 0.9, preserve = "single"), 
            vjust = 0.5,
            hjust = 1.2,
            size = 3) +
  scale_y_discrete(position = "right",
                   name = "") +
  scale_x_reverse(labels = scales::percent_format(scale = 1),
                     limits = c(25,0),
                     expand = expansion(mult = c(0, 0)),
                     name = "") +
  scale_fill_manual(values = c("#b2b8be")) + 
  theme_minimal() +
  theme(legend.position = "none",
        panel.grid.minor.x = element_blank(),
        plot.margin = unit(c(0,0,0,0), "line"))

age_plot_2022 <- alb_age_2012_2022 %>% 
  filter(year == 2022) %>% 
  ggplot(aes(y = label, x = percent, fill = factor(year))) +  # Convert year to factor here
  geom_bar(stat = "identity", position = position_dodge2(width = 0.9, preserve = "single"), width = 0.8) +
  geom_text(aes(label = scales::percent(percent / 100, accuracy = 1)), 
            position = position_dodge2(width = 0.9, preserve = "single"), 
            vjust = 0.5,
            hjust = -0.2,
            size = 3) +
  scale_y_discrete(position = "right",
                   name = "") +
  scale_x_continuous(labels = scales::percent_format(scale = 1),
                     limits = c(0,25),
                     expand = expansion(mult = c(0, 0)),
                     name = "") +
  scale_fill_manual(values = c("#ff641e")) + 
  theme_minimal() +
  theme(legend.position = "none",
        panel.grid.minor.x = element_blank(),
        axis.text.y = element_blank(),
        plot.margin = unit(c(0,0,0,0), "line"))

# age_plot_2012 + age_plot_2022
# ggarrange(age_plot_2012, age_plot_2022)

dummy_data = tibble(y = c(-25, 0, 0, 25),
                    year = c(2012, 2012, 2022, 2022))

dat <- alb_age_2012_2022 %>% 
    group_by(percent, year) %>%
    # mutate(x = sequence(n())) %>%
    mutate(y = ifelse(year == 2012, -percent, percent)) %>%
    ungroup() 

ggplot() +
  geom_bar(data = dat, 
           mapping = aes(y = y,
                         x = label,
                         fill = factor(year)),
           stat = "identity",
           width = 0.8) +
  geom_blank(data = dummy_data,
             mapping = aes(y = y)) +
  geom_text(data = dat, 
            mapping = aes(x = label, 
                          y = case_when(year == 2012 ~  y-1.2,
                                        year == 2022 ~  y+1.2),
                          label = scales::percent(percent / 100, accuracy = 1)), 
            size = 3
            ) +
  scale_x_discrete(name = "") +
  scale_y_continuous(
    # labels = scales::percent_format(scale = 1),
                     expand = expansion(mult = c(0, 0)),
                     name = "") +
    scale_fill_manual(values = c("#b2b8be", "#ff641e")) +  # Apply custom colors here
  facet_share(~ year, 
              dir = "h",
              scales = "free",
              reverse_num = TRUE) +
  coord_flip() +
  theme_light() +
  theme(legend.position = "none",
        panel.grid.minor.x = element_blank(),
        panel.border = element_blank(),
        strip.text = element_text(size = rel(1.2), 
                                  # face = "bold", 
                                  color = "black"),
    strip.background = element_rect(fill = "white", colour = "black", size = 0)
        )

```


```{r, echo=FALSE}
# Age by Sex, 2022 ----
# Albemarle

alb_sex_age_2022 <- read_csv("../data/alb_sex_age_2022.csv")
alb_sex_age_2022 <- alb_sex_age_2022 %>% 
  mutate(age_group = case_when(
    label %in% c("Under 5 years", "5 to 9 years") ~ "Under 10 years",
    label %in% c("10 to 14 years", "15 to 19 years") ~ "10 to 19 years",
    label %in% c("20 to 24 years", "25 to 34 years") ~ "20 to 34 years",
    label %in% c("35 to 44 years", "45 to 54 years") ~ "35 to 54 years",
    label %in% c("55 to 59 years", "60 to 64 years") ~ "55 to 64 years",
    label %in% c("65 to 74 years", "75 to 84 years", "85 years and over") ~ "65 years and over")) %>% 
  group_by(sex, age_group) %>% 
  summarise(percent = sum(percent)) %>% 
  mutate(age_group = factor(age_group, levels = c("Under 10 years", "10 to 19 years", "20 to 34 years",
                                                      "35 to 54 years", "55 to 64 years", "65 years and over")),
         percent_rnd = round(percent, 0))

alb_age_sex_plot <- alb_sex_age_2022 %>% 
  ggplot(aes(x = age_group, y = percent_rnd, fill = sex)) +  
  geom_bar(stat = "identity", position = position_dodge2(width = 0.9, preserve = "single"), width = 0.8) +
  geom_text(aes(label = scales::percent(percent / 100, accuracy = 1)), 
            position = position_dodge2(width = 0.9, preserve = "single"), 
            vjust = 0.5,
            hjust = -0.2,
            size = 3) +
  scale_x_discrete(expand = expansion(mult = c(0, 0)),
                   name = "") +
  scale_y_continuous(labels = scales::percent_format(scale = 1),
                     limits = c(0,20),
                     expand = expansion(mult = c(0, 0)),
                     name = "") +
  scale_fill_manual(values = c("#3B8EA5", "#b2b8be")) +  # Apply custom colors here
  coord_flip() +
  theme_minimal() +
  theme(legend.position = "top",
        panel.grid.minor.x = element_blank()) +
  # guides(fill = guide_legend(reverse = TRUE)) +
  labs(fill = "", title = "Sex by Age Groups for Albemarle, 2022")

alb_age_sex_plot


```

```{r, echo=FALSE, fig.height=3.5}
dummy_sex = tibble(y = c(-20.5, 0, 0, 20.5),
                    sex = c("Female", "Female", "Male", "Male"))

dat_sex <- alb_sex_age_2022 %>% 
    group_by(percent_rnd, sex) %>%
    # mutate(x = sequence(n())) %>%
    mutate(y = ifelse(sex == "Female", -percent_rnd, percent_rnd)) %>%
    ungroup() 

ggplot() +
  geom_bar(data = dat_sex, 
           mapping = aes(y = y,
                         x = age_group,
                         fill = sex),
           stat = "identity",
           width = 0.8) +
  geom_blank(data = dummy_sex,
             mapping = aes(y = y)) +
  geom_text(data = dat_sex, 
            mapping = aes(x = age_group, 
                          y = case_when(sex == "Female" ~  y-1.2,
                                        sex == "Male" ~  y+1.2),
                          label = scales::percent(percent / 100, accuracy = 1)), 
            size = 3
            ) +
  scale_x_discrete(name = "") +
  scale_y_continuous(
    # labels = scales::percent_format(scale = 1),
                     expand = expansion(mult = c(0, 0)),
                     name = "") +
  scale_fill_manual(values = c("#3B8EA5", "#b2b8be")) +  # Apply custom colors here
  facet_share(~ sex, 
              dir = "h",
              scales = "free",
              reverse_num = TRUE) +
  coord_flip() +
  theme_light() +
  theme(legend.position = "none",
        panel.grid.minor.x = element_blank(),
        panel.border = element_blank(),
        strip.text = element_text(size = rel(1.2), 
                                  # face = "bold", 
                                  color = "black"),
    strip.background = element_rect(fill = "white", colour = "black", size = 0)
        )


```


```{r, echo=FALSE, fig.width=10, fig.height=3}

# Albemarle, Resident Status & Foreign Born, 2022 ----
alb_nativity_2022 <- read_csv("../data/alb_nativity_2022.csv")
alb_nativity_2022 <- alb_nativity_2022 %>% 
  mutate(status = case_when(
    label == "U.S. citizen, born in the United States" ~ "US-born",
    label == "U.S. citizen, born in Puerto Rico or U.S. Island Areas" ~ "US-born",
    label == "U.S. citizen, born abroad of American parent(s)" ~ "US-born",
    label == "U.S. citizen by naturalization" ~ "Foreign-born",
    label == "Not a U.S. citizen" ~ "Foreign-born"
  )) %>% 
  group_by(GEOID, locality, status, total_pop, year) %>% 
  summarise(estimate = sum(estimate))

# Compute percentages
alb_nativity_2022$fraction = alb_nativity_2022$estimate / alb_nativity_2022$total_pop
# Compute the cumulative percentages (top of each rectangle)
alb_nativity_2022$ymax = cumsum(alb_nativity_2022$fraction)
# Compute the bottom of each rectangle
alb_nativity_2022$ymin = c(0, head(alb_nativity_2022$ymax, n=-1))

# Plot the donut chart
alb_nativity_chart_2022 <- ggplot(alb_nativity_2022, aes(ymax = ymax, ymin = ymin, xmax = 4, xmin = 3, fill = status)) +
  geom_rect(color = "white") +
  coord_polar(theta = "y") +
  xlim(c(1.5, 4)) +
  scale_fill_manual(values = c("#8856A7", "#b2b8be")) +
  geom_text(aes(label = paste0(round(fraction * 100, 0), "%"), x = 3.5, y = (ymin + ymax) / 2)) +
  theme_void() +
  theme(legend.position = c(.525, .5)) +
  theme(legend.title = element_blank()) +
  theme(legend.text = element_text(size = 8)) +
  labs(title = "Nativity of Albemarle Residents, 2022")

# stacked bar
alb_nativity_stacked <- alb_nativity_2022 %>% 
  mutate(percent = round(estimate/total_pop *100, 0),
         text = paste0(round(percent, 0), "%"),
         status = factor(status, levels = c("US-born","Foreign-born"))) %>% 
  arrange(status) %>% 
  ggplot(aes(x = percent, y = locality, group = locality, fill = status, label = text)) +
  geom_bar(stat = "identity", color = "white") +
  geom_text(size = 3, position = position_stack(vjust = 0.5)) +
  scale_x_continuous(labels = label_percent(scale = 1),
                     name = "") +
  scale_y_discrete(name = "") +
  labs(color = "", title = "Nativity of Albemarle Residents, 2022") +
  scale_fill_manual(values = c("#b2b8be", "#8856A7")) +  
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "top",
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.text.y = element_blank())

ggarrange(alb_nativity_chart_2022, alb_nativity_stacked, nrow = 1)

```

```{r, echo=FALSE, fig.width=10}
pal_6 <- c("#BFD3E6", "#9EBCDA", "#8C96C6", "#8C6BB1", "#88419D", "#6E016B")

# Albemarle, Foreign-born by location, 2022 ----
alb_foreign_born <- read_csv("../data/alb_birth_place_foreign_2022.csv")
alb_foreign_born <- alb_foreign_born %>% 
  mutate(region = case_when(str_detect(label, "Europe") ~ "Europe",
                            str_detect(label, "Asia") ~ "Asia",
                            str_detect(label, "Africa") ~ "Africa",
                            str_detect(label, "Latin America") ~ "Latin America",
                            .default = label),
         percent_rnd = round(percent,0))

alb_donut_dat <- alb_foreign_born %>% 
  group_by(region) %>% 
  summarise(estimate = sum(estimate),
            total_foreign_born = first(total_foreign_born))
# Compute percentages
alb_donut_dat$fraction = alb_donut_dat$estimate / alb_donut_dat$total_foreign_born
# Compute the cumulative percentages (top of each rectangle)
alb_donut_dat$ymax = cumsum(alb_donut_dat$fraction)
# Compute the bottom of each rectangle
alb_donut_dat$ymin = c(0, head(alb_donut_dat$ymax, n=-1))

# Plot the donut chart
alb_foreign_born_donut <- alb_donut_dat %>% 
  filter(round(fraction, 2) >= 0.01) %>% 
  ggplot(aes(ymax = ymax, ymin = ymin, xmax = 4, xmin = 3, fill = region)) +
  geom_rect(color = "white") +
  coord_polar(theta = "y") +
  xlim(c(1.5, 4)) +
  scale_fill_manual(values = pal_6) +
  geom_text(aes(label = paste0(round(fraction * 100, 0), "%"), x = 3.5, y = (ymin + ymax) / 2)) +
  theme_void() +
  theme(legend.position = c(.525, .5)) +
  theme(legend.title = element_blank()) +
  theme(legend.text = element_text(size = 8)) +
  labs(title = "Foreign-Born Albemarle Residents, by place of birth, 2022")


# Bar chart
alb_foreign_born_plot <- alb_foreign_born %>% 
  mutate(percent = round(percent, 0),
         label = factor(label,
                        levels = c("Oceania",
                                   "Southern Africa","Middle Africa","Northern Africa","Eastern Africa","Western Africa",   
                                   "Northern America", 
                                   "Southern Europe","Western Europe","Eastern Europe","Northern Europe",   
                                   "Latin America, Caribbean","Latin America, South America","Latin America, Central America",  
                                   "South Eastern Asia","Western Asia","South Central Asia", "Eastern Asia"  
                        ))) %>%
  filter(percent >= 1) %>%
  ggplot(aes(x = percent, y = label, fill = region)) +  
  geom_bar(stat = "identity") +
  geom_text(aes(label = scales::percent(percent / 100, accuracy = 1)), 
            # position = position_dodge2(width = 0.9, preserve = "single"), 
            vjust = 0.5,
            hjust = -0.2,
            size = 3) +
  scale_x_continuous(labels = scales::percent_format(scale = 1),
                     limits = c(0,26),
                     expand = expansion(mult = c(0, 0)),
                     name = "") +
  scale_y_discrete(name = "") +
  scale_fill_manual(values = pal_6) +
  theme_minimal() +
  theme(legend.position = "top",
        panel.grid.minor.x = element_blank()) +
  labs(fill = "", title = "")

ggarrange(alb_foreign_born_donut, alb_foreign_born_plot, nrow = 1)

```



```{r, echo=FALSE, fig.height=3, fig.width=6}
# Household Language, Limited English Speaking Status ----
# Albemarle, 2022
alb_language <- read.csv("../data/alb_language_2022.csv")

# All households summarized
alb_lang_all <- alb_language %>% 
  mutate(status = case_when(str_detect(label, "Not a limited English speaking household") ~ "Multi-lingual houshold, incld. English",
                            str_detect(label, "Limited English speaking household") ~ "Limited English speaking household",
                            .default = label)) %>% 
  group_by(status, locality) %>% 
  summarise(estimate = sum(estimate),
            total_households = first(total_households),
            percent = round(estimate/total_households *100, 1))

# Compute percentages
alb_lang_all$fraction = alb_lang_all$estimate / alb_lang_all$total_households
# Compute the cumulative percentages (top of each rectangle)
alb_lang_all$ymax = cumsum(alb_lang_all$fraction)
# Compute the bottom of each rectangle
alb_lang_all$ymin = c(0, head(alb_lang_all$ymax, n=-1))

# Plot the donut chart
alb_lang_donut <- alb_lang_all %>%
  mutate(status = factor(status, levels = c("English only","Multi-lingual houshold, incld. English","Limited English speaking household"))) %>%
  ggplot(aes(ymax = ymax, ymin = ymin, xmax = 4, xmin = 3, fill = status)) +
  geom_rect(color = "white") +
  coord_polar(theta = "y") +
  xlim(c(1.5, 4)) +
  scale_fill_manual(values = c("#b2b8be","#8C96C6", "#6E016B")) +
  geom_label_repel(aes(label = paste0(round(percent, 0), "%\n", scales::comma(estimate), " households"),
                       x = 3.5, y = (ymin + ymax) / 2),
                   size = 3, fontface = "bold", 
                   show.legend = FALSE,
                   # min.segment.length = Inf,
                   # position = position_stack(vjust = 0.5),
                   # box.padding = 0.5,
                   # force_pull = 400,
                   # direction = "x",
                   color = "white",
                   seed = 123) +
  # geom_text(aes(label = paste0(round(percent, 0), "%\n", scales::comma(estimate), " households"), x = 3.5, y = (ymin + ymax) / 2)) +
  theme_void() +
  # theme(legend.position = c(.525, .5)) +
  theme(legend.title = element_blank()) +
  theme(legend.text = element_text(size = 8)) +
  labs(title = "Albemarle household languages, 2022")

# alb_lang_donut

# stacked bar
alb_lang_stacked <- alb_lang_all %>% 
  mutate(text = paste0(round(percent, 0), "%\n", scales::comma(estimate), " households"),
         status = factor(status, levels = c("English only","Multi-lingual houshold, incld. English","Limited English speaking household"))) %>% 
  arrange(status) %>% 
  ggplot(aes(x = percent, y = locality, group = locality, fill = status, label = text)) +
  geom_bar(stat = "identity", color = "white") +
  coord_cartesian(clip = "off") +
  geom_label_repel(aes(label = text),
                   size = 3, fontface = "bold", show.legend = FALSE,
                   # min.segment.length = Inf,
                   position = position_stack(vjust = 0.5), 
                   box.padding = 0.1,
                   # force_pull = 100,
                   # direction = "y",
                   color = "white",
                   seed = 123) +
  # geom_text_repel(
  #   position = position_stack(vjust = 0.5), 
  #   box.padding = 0.05,
  #   # min.segment.length = Inf,
  #   xlim = c(NA, Inf),
  #   force_pull = 100,
  #   nudge_y = -0.5,
  #   # nudge_x = 1,
  #   direction = "y"
  # ) +
  # geom_text(size = 3, position = position_stack(vjust = 0.5)) +
  scale_x_continuous(labels = label_percent(scale = 1),
                     breaks = pretty_breaks(),
                     name = "",
                     expand = expansion(mult = c(0, .15))) +
  scale_y_discrete(name = "") +
  labs(color = "", title = "Albemarle household languages, 2022") +
  scale_fill_manual(values = c("#b2b8be", "#8C96C6", "#6E016B")) +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "top",
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.text.y = element_blank())

alb_lang_stacked
```

```{r, echo=FALSE, fig.height=5, fig.width=8}
# Household, by language and status ---
alb_lang_stat <- alb_language %>% 
  filter(label != "English only") %>% 
  separate(label, c("group", "status"), sep = ": ")

alb_lang_stat$total_non_eng = sum(alb_lang_stat$estimate)

alb_lang_stat <- alb_lang_stat %>%
  mutate(limited = case_when(
    estimate == 0 ~ group,
    .default = NA
  )) %>% 
  filter(!group %in% limited) %>% 
  select(GEOID, locality, estimate, total_non_eng, group, status, year, total_households)

# stacked bar
alb_lang_stat_stacked <- alb_lang_stat %>% 
  mutate(group = factor(group, levels = c("Other and unspecified languages","Arabic",
                                          "Other Asian and Pacific Island languages","Tagalog (incl. Filipino)","Vietnamese","Chinese (incl. Mandarin, Cantonese)","Korean", 
                                          "Other Indo-European languages","Russian, Polish, or other Slavic languages","German or other West Germanic languages","French, Haitian, or Cajun","Spanish")  )) %>% 
  arrange(group) %>% 
  ggplot(aes(x = estimate, y = group, group = group, fill = status, label = scales::comma(estimate))) +
  geom_bar(stat = "identity", color = "white") +
  # geom_label_repel(aes(label = scales::comma(estimate)),
  #                  size = 3.5, fontface = "bold", show.legend = FALSE,
  #                  # min.segment.length = Inf,
  #                  position = position_stack(vjust = 0.5),
  #                  box.padding = 0.1,
  #                  # force_pull = 100,
  #                  direction = "x",
  #                  color = "white") +
  geom_label_repel(aes(label = scales::comma(estimate)), 
                   # position = position_stack(vjust = 0.9),
            # position = position_dodge2(width = 0.5, preserve = "single"), 
            vjust = 0.5,
            # hjust = -0.1,
            nudge_x = -5,
            direction = "x",
            size = 3, fontface = "bold",
            color = "white",
            show.legend = FALSE,
                   seed = 123) +
  # geom_text(size = 3, position = position_stack(vjust = 0.5)) +
  scale_x_continuous(name = "Number of Households") +
  scale_y_discrete(name = "") +
  labs(color = "", title = "Albemarle languages by household and status, 2022") +
  scale_fill_manual(values = c("#6E016B", "#8C96C6")) +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "top",
        panel.grid.minor.y = element_blank(),
        # panel.grid.major.y = element_blank()
        )

alb_lang_stat_stacked

```

```{r, echo=FALSE}
# Disability Status ----
# Albemarle, 2022
alb_disability_age <- read_csv("../data/alb_disability_2022.csv")

# Wrangle by age groups
alb_disability_dat <- alb_disability_age %>% 
  group_by(disability_status, age_group, locality, year) %>% 
  summarise(estimate = sum(estimate),
            total_pop = first(total_pop))

alb_disability_stat <- alb_disability_age %>% 
  group_by(age_group, locality, year) %>% 
  summarise(total_age = sum(estimate))

alb_dis <- alb_disability_dat %>% left_join(alb_disability_stat) %>% 
  mutate(per_age_group = round(estimate/total_age * 100, 2))

# Grouped bar chart (as percent of total pop)
alb_dis_age_stacked_a <- alb_disability_dat %>% 
  mutate(percent = case_when(round(estimate/total_pop * 100, 2) < 1 ~ round(estimate/total_pop * 100, 2),
                             round(estimate/total_pop * 100, 2) >= 1 ~ round(estimate/total_pop * 100, 0)),
         label = case_when(percent < 1 ~ paste0(scales::percent(percent / 100, accuracy = 0.1), " (", scales::comma(estimate),")"),
                           percent >= 1 ~ paste0(scales::percent(percent / 100, accuracy = 1), " (", scales::comma(estimate),")"))
         )%>% 
  ggplot(aes(x = round(percent, 1), y = age_group, group = age_group, fill = disability_status, label = scales::comma(estimate))) +
  # geom_bar(stat = "identity") +
  geom_bar(stat = "identity", position = position_dodge2(width = 0.9, preserve = "single"), width = 0.8) +
  geom_text(aes(label = label), 
            position = position_dodge2(width = 0.9, preserve = "single"), 
            vjust = 0.5,
            hjust = -0.1,
            size = 3) +
  scale_x_continuous(labels = scales::percent_format(scale = 1),
                     limits = c(0,45),
                     expand = expansion(mult = c(0, 0)),
                     name = "") +
  scale_y_discrete(name = "") +
  scale_fill_manual(values = c("#b2b8be","#3B8EA5")) +
  labs(color = "", title = "Albemarle disability status by age, 2022\n(as percent of total population)") +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "top",
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_blank())


# As percents of age group
alb_dis_by_age_stacked <- alb_dis %>% 
  mutate(label = paste0(scales::percent(per_age_group / 100, accuracy = 1), "\n(",
                        scales::comma(estimate), ")"),
         disability_status = factor(disability_status, levels = c("With a disability","No disability"))) %>% 
  arrange(disability_status) %>% 
  ggplot(aes(x = round(per_age_group, .1), y = age_group, group = age_group, fill = disability_status, label = label)) +
  geom_bar(stat = "identity", color = "white") +
  geom_label_repel(aes(label = label),
                   size = 3, fontface = "bold", show.legend = FALSE,
                   # min.segment.length = Inf,
                   position = position_stack(vjust = 0.5),
                   # box.padding = 0.1,
                   # force_pull = 100,
                   direction = "x",
                   color = "white",
                   seed = 123) +
  # geom_text(position = position_dodge2(width = 0.5, preserve = "single"), 
  #           vjust = 0.5,
  #           hjust = -0.2,
  #           size = 3) +
  scale_x_continuous(labels = scales::percent_format(scale = 1),
                     limits = c(0,100),
                     name = "") +
  scale_y_discrete(name = "") +
  scale_fill_manual(values = c("No disability"="#b2b8be","With a disability"="#3B8EA5")) +
  labs(color = "", title = "Albemarle disability status, 2022\n (as percent of age group)") +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "top",
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_blank())

alb_dis_by_age_stacked

# ggarrange(alb_dis_age_stacked_a, alb_dis_by_age_stacked, nrow=1)

```

```{r, echo=FALSE}
# Disability categories ----
alb_disability_cat <- read_csv("../data/alb_disability_cat_2022.csv")
alb_disability_cat <- alb_disability_cat %>% 
  mutate(label = str_remove(label, "With a "),
         label = str_remove(label, "With an "),
         label = str_replace(label, " difficulty", "\ndifficulty"),
         # label = str_replace(label, " living", "\nliving"),
         label = str_to_title(label))

dis_donut <- alb_disability_cat %>%
  mutate(label = factor(label, levels = c("Vision\nDifficulty", "Self-Care\nDifficulty", "Hearing\nDifficulty", "Cognitive\nDifficulty", "Independent Living\nDifficulty", "Ambulatory\nDifficulty"))) %>% 
ggplot(aes(x = 2, y = percent, fill = label)) +
  geom_bar(stat = "identity", width = 1, color = "white") +
  coord_polar(theta = "y") +
  xlim(0.5, 3.2) +
  geom_text(aes(label = paste0(round(percent, 0), "%")),
            position = position_stack(vjust = 0.5),
            color = "white", fontface = "bold") +
  # geom_text(aes(label = label, x = 3.15),
  #           position = position_stack(vjust = 0.5)) +
  geom_label_repel(aes(label = label, x = 3.15),
                   size = 3, 
                   fontface = "bold",
                   position = position_stack(vjust = 0.5),
                   force = 0,
                   color = "white",
                   # nudge_x = 1, 
                   # direction = "x",
                   # min.segment.length = 0,
                   # box.padding = 0.5,
                   # segment.curvature = -0.1,
                   # segment.ncp = 3,
                   # segment.angle = 20,
                   seed = 123
  ) +
  scale_fill_manual(values = c("#3CA69A", "#3C6DA6", "#3C8FA6", "#3CA676", "#3C4CA6", "#739BA6")) +
  # geom_segment(aes(x = 2.5, xend = 2.8, y = 2, yend = 2.1)) +
  labs(fill = "Category",title = "Albemarle Disability Status by type for 2022") +
  theme_void() +
  theme(legend.position = "none")

# bar chart
dis_bar <- alb_disability_cat %>%
  mutate(label = factor(label, levels = c("Vision\nDifficulty", "Self-Care\nDifficulty", "Hearing\nDifficulty", "Cognitive\nDifficulty", "Independent Living\nDifficulty", "Ambulatory\nDifficulty"))) %>%
  ggplot(aes(x = reorder(label, -estimate), y = estimate)) +
  coord_flip() +
  geom_bar(stat = "identity", width = 0.7, fill = "#3B8EA5") +
  geom_text(aes(label = scales::comma(estimate)), 
            # position = position_stack(vjust = 0.5),
            vjust = 0.5,
            hjust = -0.2,
            size = 3,
            color = "black") +
  scale_y_continuous(expand = expansion(mult = c(0, .1))) +
  labs(
    x = "",
    y = "Number of people with a disability",
    title = "Albemarle Disability Status by type for 2022"
  ) +
  theme_minimal() +
  theme(legend.position = "none")

dis_bar

# ggarrange(dis_donut, dis_bar, nrow = 1)

```

