---
title: "Equity Profile Access to Knowledge - Charlottesville"
output: html_document
---

```{css, echo=FALSE}
.main-container.container-fluid {
max-width: 1200px;
  margin-left: auto;
  margin-right: auto;
  padding: 0 4.167%;
}

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# Load packages ----
library(tidyverse)
library(scales)
library(RColorBrewer)
library(ggspatial)
library(tigris)
library(readxl)
library(stringr)
library(sf)
library(ggthemes)
library(rcartocolor)

# Education palette ----
# pal_edu <- colorRampPalette(brewer.pal(9, "PuRd"))(15)
pal_edu <- carto_pal(7, "PinkYl")

# Tract geometries ----
cville_geo <- tracts(state = "VA", county = "540")

# Common Items ----
locality_name <- "City of Charlottesville"
school_district <- "Charlottesville City Schools (CCS)"
source_acs <- "Data Source: American Community Survey, 2022"
source_vdoe <- "Data Source: Virginia Department of Education, 2022-2023"

```

```{r, echo=FALSE, fig.height=8}
# School Enrollment: Charlottesville, 2022 ----
cville_enroll_tract <- read_csv("../data/cville_enroll_tract_2022.csv") %>%
  mutate(GEOID = as.character(GEOID))

cville_enroll_tract <- cville_enroll_tract %>%
  left_join(cville_geo, by = "GEOID") %>% 
  st_as_sf()

# Geospatial visualization
cville_enroll_map <- cville_enroll_tract %>% 
  mutate(percent = round(percent, 0),
         text = paste0(percent, "%")) %>% 
  ggplot() +
    annotation_map_tile(zoomin = 1, progress = "none", cachedir = "../data/tempdata/") +
  geom_sf(aes(fill = percent), color = "white") +
  geom_sf_text(aes(label = text), size = 3, color = "black") +
  # theme_map() +
  #   theme(
  #     legend.position = "bottom",
  #     plot.title = element_text(hjust = 0.5),
  #     plot.subtitle = element_text(hjust = 0.5)
  #     ) +
  # scale_fill_viridis_b()+
  # scale_fill_gradient2(midpoint = 80, guide = guide_colorbar()) +
  # scale_fill_continuous(guide = guide_colorbar()) +
  # scale_fill_binned()+
  scale_fill_stepsn(colors = pal_edu,
                    labels = scales::label_percent(scale = 1),
                      n.breaks = 6,
                    guide = guide_colourbar(title = "Percent Enrolled",
                                            title.position = "top",
                                            direction = "horizontal",
                                            title.hjust = 0.5,
                                            # nbin = 6,
                                            theme = theme(legend.key.height  = unit(0.5, "lines"),
                                                          legend.key.width = unit(12, "lines"),
                                                          text = element_text(size = 11,
                                                                              # face = "bold",
                                                                              # colour = "gray30"
                                                                              )) 
                                            )
                    )+
  labs(title = "School Enrollment (Ages 3-24)", 
      subtitle = locality_name, 
      caption = source_acs) +
  theme_map()+
  theme(
    # legend.position="top",
        legend.position.inside=c(1, 1.04),
        legend.justification="right",
        # legend.justification = "center",
        plot.title = element_text(size = 14),
        plot.subtitle = element_text(size = 14)
        )

cville_enroll_map

```

```{r, echo=FALSE}
# Educational Attainment by Race (25 Years and Over) Charlottesville, 2022 ----
cville_edu_attain_race <- read_csv("../data/cville_edu_attain_race_county_2022.csv")

cville_edu_attain_race_plot <- cville_edu_attain_race %>% 
  filter(group_total != 0) %>% 
  filter(race != "White") %>% 
  mutate(label = factor(edu_level, 
                        levels = c("less_than_hs", 
                                   "hs_only", 
                                   "bachelors_up"), 
                        labels = c("Less than a HS diploma", "High School diploma, no college", "Bachelor's degree or higher")),
         race = factor(race,
                       levels = c("Amer_Indian", "Asian", "Black", "Hispanic", "Multi", "NHPI", "Other", "White_non_hisp"),
                       labels = c("American Indian", "Asian", "Black", "Hispanic", "Multiracial", "Native Hawaiian/Pacific Islander", "Other Racial Identities", "White")),
         text = case_when(percent >= 1 ~ paste0(round(percent, 0), "%"),
                          percent < 1 ~ "")
  )

# Stacked bar
cville_edu_race_plot <- cville_edu_attain_race_plot %>% 
  filter(!race %in% c("Other Racial Identities")) %>% 
  filter(group_total >= 400) %>% 
  ggplot(aes(x = race, y = percent, group = race, fill = label, 
             label = text)) +
  geom_bar(stat = "identity", color="white") + 
  geom_text(size = 3, position = position_stack(vjust = 0.5)) +
  scale_fill_manual(values = c("#3B8EA5", "#8C96C6", "#FFA679")) +
  # scale_fill_manual(values = c("#FEF6B5", "#FFA679", "#E15383")) +
  scale_x_discrete(name = "") +
  scale_y_continuous(labels = label_percent(scale = 1),
                     name = "") +
  labs(title = "Educational Attainment by Race/Ethnicity (25 Years and Over)", 
       subtitle = locality_name,
       caption = source_acs) +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "top",
        panel.grid.major.x = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.minor = element_blank())

cville_edu_race_plot

```

```{r, echo=FALSE, fig.height=8}
# Educational Attainment, with BA's by tract, Charlottesville, 2022 ----
cville_edu_attain_tract <- read_csv("../data/cville_edu_attain_tract_2022.csv") %>%
  mutate(GEOID = as.character(GEOID))

cville_edu_attain_tract <- cville_edu_attain_tract %>%
  left_join(cville_geo, by = "GEOID") %>% 
  st_as_sf()

cville_attain_BAs <- cville_edu_attain_tract %>%
  filter(label == "Bachelor's degree or higher")

# Geospatial visualization
cville_educ_attain_map <- cville_attain_BAs %>% 
  mutate(percent = round(percent, 0),
         text = paste0(percent, "%")) %>% 
  ggplot() +
  annotation_map_tile(zoomin = 1, progress = "none", cachedir = "../data/tempdata/") +
  geom_sf(aes(fill = percent), color = "white") +
  geom_sf_text(aes(label = text), size = 3, color = "black") +
  scale_fill_stepsn(colors = pal_edu,
                    labels = scales::label_percent(scale = 1),
                      n.breaks = 6,
                    guide = guide_colourbar(title = "Percent BA or Higher",
                                            title.position = "top",
                                            direction = "horizontal",
                                            title.hjust = 0.5 ,
                                            # nbin = 6,
                                            theme = theme(legend.key.height  = unit(0.5, "lines"),
                                                          legend.key.width = unit(12, "lines"),
                                                          # legend.key.width  = unit(1, "lines"),
                                                          # legend.key.height = unit(10, "lines"),
                                                          text = element_text(size = 11,
                                                                              # face = "bold",
                                                                              # colour = "gray40"
                                                                              )) )
                    )+
  labs(title = "Education Level: Bachelor's Degree or Higher", 
      subtitle = locality_name, 
      caption = source_acs) +
  theme_map()+
  theme(legend.position.inside=c(1, 1.04),
        legend.justification="right",
        # legend.position="right",
        # legend.justification = "center",
        plot.title = element_text(size = 14),
        plot.subtitle = element_text(size = 14)
        )

cville_educ_attain_map

```

```{r, echo=FALSE}
# Advanced Courses, AP & Dual Enrollment: Charlottesville ----

cville_adv_enroll <- read_csv("../data/cville_adv_enroll_2022_2023.csv")  

# AP & Dual Enrollment
cville_adv_enroll %>% 
  filter(! label %in% c("American Indian or Alaska Native", "Native Hawaiian or Pacific Islander")) %>% 
  select(label, ap_percent, dual_percent) %>% 
  pivot_longer(ap_percent:dual_percent, names_to = "type") %>% 
  mutate(label = factor(label,
                        levels = c("All Students", "Economically Disadvantaged",
                                   "Asian", "Black, not of Hispanic origin", "Hispanic",
                                   "Non-Hispanic, two or more races", "White, not of Hispanic origin"),
                        labels = c("All Students", "Economically \nDisadvantaged",
                                   "Asian", "Black", "Hispanic",
                                   "Multiracial", "White")),
         type = factor(type,
                       levels = c("ap_percent", "dual_percent"),
                       labels= c("Students taking 1 or more AP Courses", "Students taking 1 or more Dual Enrollment Courses")),
         value = round(value, 0),
         text = paste0(value, "%")) %>% 
  ggplot(aes(x = label, y = value, fill = type)) +
  geom_bar(stat = "identity", position = position_dodge2(width = 0.9, preserve = "single"), width = 0.8) + 
  geom_text(aes(label = text), 
              position = position_dodge2(width = 0.9, preserve = "single"), 
              vjust = -1,
              # hjust = -0.2,
              size = 3) +
  scale_x_discrete(name = "") +
  scale_y_continuous(labels = label_percent(scale = 1),
                     limits = c(0,100),
                     name = "") +
  scale_fill_manual(values = c("#3B8EA5", "#8C96C6")) +
  labs(title = "AP & Dual Enrollment",
       subtitle = school_district, 
       caption = source_vdoe) +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "top",
        panel.grid.major.x = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.minor = element_blank())

# Short Term Suspensions: Charlottesville ----
cville_suspensions <- read_csv("../data/cville_st_suspensions_2022_2023.csv")  

cville_suspensions %>% 
  filter(! subgroup %in% c("American Indian", "Native Hawaiian")) %>% 
  select(subgroup, percent_of_the_student_population, percent_of_short_term_suspensions) %>% 
  pivot_longer(percent_of_the_student_population:percent_of_short_term_suspensions, names_to = "type") %>% 
  mutate(subgroup = factor(subgroup,
                        levels = c("White", "Multiple Races", "Hispanic", "Black", "Asian")),
         type = factor(type,
                       levels = c("percent_of_the_student_population", "percent_of_short_term_suspensions"),
                       labels= c("Percent of the student population", "Percent of short term suspensions")),
         value = round(value, 0),
         text = paste0(value, "%")) %>% 
  ggplot(aes(x = subgroup, y = value, fill = type)) +  
  geom_bar(stat = "identity", position = position_dodge2(width = 0.9, preserve = "single"), width = 0.8) +
  geom_text(aes(label = text), 
            position = position_dodge2(width = 0.9, preserve = "single"), 
            vjust = 0.5,
            hjust = -0.2,
            size = 3) +
  scale_x_discrete(name = "") +
  scale_y_continuous(labels = scales::percent_format(scale = 1),
                     limits = c(0,100),
                     expand = expansion(mult = c(0, 0)),
                     name = "") +
  scale_fill_manual(values = c("#b2b8be", "#ff641e")) + 
  coord_flip() +
  theme_minimal() +
  theme(legend.position = "top",
        panel.grid.minor.x = element_blank()) +
  guides(fill = guide_legend(reverse = TRUE)) +
  labs(fill = "", 
       title = "Short Term Suspension Incidents by Race/Ethnicity",
       subtitle = school_district, 
       caption = source_vdoe)

```

```{r, echo=FALSE, fig.width=9}
# Chronic Absenteeism: Charlottesville ----
cville_absent <- read_csv("../data/cville_absenteeism_2022_2023.csv")  

cville_absent %>% 
  filter(! subgroup %in% c("American Indian", "Native Hawaiian")) %>% 
  mutate(subgroup = factor(subgroup,
                        levels = c("All Students", "Economically Disadvantaged", "Students with Disabilities",
                                   "Male", "Female",
                                   "Asian", "Black", "Hispanic", "Multiple Races", "White"),
                        labels = c("All Students", "Economically \nDisadvantaged", "Students with \nDisabilities",
                                   "Male", "Female",
                                   "Asian", "Black", "Hispanic", "Multiracial", "White")),
         percent_above_10 = round(percent_above_10, 0),
         text = paste0(percent_above_10, "%")) %>% 
  ggplot(aes(x = subgroup, y = percent_above_10)) +
  geom_bar(stat = "identity", width = 0.7, fill = "#3B8EA5") + 
  geom_text(aes(label = text), 
            vjust = -1,
            size = 3,
            color = "black") +
  scale_x_discrete(name = "") +
  scale_y_continuous(labels = label_percent(scale = 1),
                     limits = c(0,60),
                     name = "") +
  labs(title = "Chronic Absenteeism",
       subtitle = school_district, 
       caption = source_vdoe) +
  theme_minimal() +
  theme(legend.title=element_blank(),
        panel.grid.major.x = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.minor = element_blank())



```

