---
title: "Equity Profile Access to Knowledge - Albemarle"
output: html_document
---

```{css, echo=FALSE}
.main-container.container-fluid {
max-width: 1200px;
  margin-left: auto;
  margin-right: auto;
  padding: 0 4.167%;
}

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# Load packages ----
library(tidyverse)
library(scales)
library(RColorBrewer)
library(ggspatial)
library(tigris)
library(readxl)
library(stringr)
library(sf)
library(ggthemes)
library(rcartocolor)
library(patchwork)

# Education palette ----
# pal_edu <- colorRampPalette(brewer.pal(9, "PuRd"))(15)
pal_edu <- carto_pal(7, "PinkYl")

# Tract geometries ----
alb_geo <- tracts(state = "VA", county = "003")

# Common Items ----
locality_name <- "Albemarle County"
school_district <- "Albemarle County Public Schools (ACPS)"
source_acs <- "Data Source: American Community Survey, 2022"
source_vdoe <- "Data Source: Virginia Department of Education, 2022-2023"

```

```{r, echo=FALSE, fig.height=9, fig.width=11}
# School Enrollment: Albemarle, 2022 ----
alb_enroll_tract <- read_csv("../data/alb_enroll_tract_2022.csv") %>%
  mutate(GEOID = as.character(GEOID),
         percent = round(percent, 0))

alb_enroll_tract <- alb_enroll_tract %>%
  left_join(alb_geo, by = "GEOID") %>% 
  st_as_sf()

# Geospatial visualization
alb_enroll_map <- alb_enroll_tract %>% 
  mutate(text = paste0(percent, "%")) %>% 
  ggplot() +
    annotation_map_tile(zoomin = 1, progress = "none", cachedir = "../data/tempdata/") +
  geom_sf(aes(fill = percent), color = "white") +
  geom_sf_text(aes(label = text), size = 2.5, color = "black") +
  # theme_map() +
  #   theme(
  #     legend.position = "bottom",
  #     plot.title = element_text(hjust = 0.5),
  #     plot.subtitle = element_text(hjust = 0.5)
  #     ) +
  # scale_fill_viridis_b()+
  # scale_fill_gradient2(midpoint = 80, guide = guide_colorbar()) +
  # scale_fill_continuous(guide = guide_colorbar()) +
  # scale_fill_binned()+
  scale_fill_stepsn(colors = pal_edu,
                    labels = scales::label_percent(scale = 1),
                      n.breaks = 6,
                    guide = guide_colourbar(title = "Percent Enrolled",
                                            title.position = "top",
                                            direction = "horizontal",
                                            title.hjust = 0.5,
                                            # nbin = 6,
                                            theme = theme(legend.key.height  = unit(0.5, "lines"),
                                                          legend.key.width = unit(12, "lines"),
                                                          text = element_text(size = 11,
                                                                              # face = "bold",
                                                                              # colour = "gray30"
                                                                              )) 
                                            )
                    )+
  # labs(title = "School Enrollment (Ages 3-24)", 
  #     subtitle = locality_name, 
  #     caption = source_acs) +
  theme_map()+
  theme(
    # legend.position="top",
        legend.position.inside=c(1, 1.04),
        legend.justification="right",
        # legend.justification = "center",
        plot.title = element_text(size = 14),
        plot.subtitle = element_text(size = 14)
        )

# Rank plot
alb_enroll_data <- alb_enroll_tract %>%
  group_by(percent) %>% 
  summarise(tractnames = paste(tractnames, collapse = "; ")) %>% 
  na.exclude() 

names <- alb_enroll_data$tractnames
enrollment <- alb_enroll_data$percent

alb_enroll_rank <- ggplot(alb_enroll_data, aes(x = 0, y = percent, label = names)) +
    geom_line(color = "grey", size = 1)+
    geom_point(aes(color=as.factor(percent)), size=5)+
    geom_text(label = str_wrap(names, width = 50), hjust = 0, nudge_x = 0.006, 
              nudge_y = 0.03,
              size = 3.5,
              lineheight = 0.8) +
   scale_color_carto_d(name = "Percent Enrolled: ",
                           type = "diverging", palette = "PinkYl", direction = 1) +
    scale_x_continuous(limits = c(0,.1),
                       expand = c(0.03, 0.003))+
    scale_y_continuous(
                       breaks = enrollment,
                       labels = paste0(enrollment, "%")
                       ) +
  theme_minimal()+
    theme(axis.line.x = element_blank(),
          axis.ticks.x = element_blank(),
          axis.text.x = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          panel.grid.minor = element_blank(),
          panel.grid.major = element_blank(),
          axis.text.y = element_text(size = 11),
          axis.ticks = element_line(linewidth = .5),
          axis.ticks.length.y = unit(.25, "cm"),
          plot.title.position= "plot",
          plot.caption.position = "plot",
          plot.caption = element_text(hjust = 0),
          legend.position="none")
  
  (alb_enroll_map + patchwork::free(alb_enroll_rank)) +
  plot_layout(widths = c(1.75, 1)) +
  plot_annotation(title = "School Enrollment (Ages 3-24)", 
      subtitle = locality_name, 
      caption = source_acs)


```

```{r, echo=FALSE}
# Educational Attainment by Race (25 Years and Over) Albemarle, 2022 ----
alb_edu_attain <- read_csv("../data/alb_edu_attain_county_2022.csv") %>% 
  select(-percent) %>% 
  mutate(label = case_when(label == "High school graduate or higher" ~ "high_school_up",
                     label == "Bachelor's degree or higher" ~ "bachelors_up",
                     label == "Graduate or professional degree" ~ "grad")) %>% 
  pivot_wider(names_from = label, values_from = c(estimate, moe)) %>% 
  mutate(less_than_hs = pop_25_over - estimate_high_school_up,
         hs_only = estimate_high_school_up - estimate_bachelors_up) %>% 
  rename(bachelors_up = estimate_bachelors_up, 
         group_total = pop_25_over) %>% 
  select(GEOID, locality, less_than_hs, hs_only, bachelors_up, group_total, year)
# Return to long, add percents, prep for data viz
alb_edu_attain <- alb_edu_attain %>% 
  pivot_longer(less_than_hs:bachelors_up) %>% 
  mutate(percent = round(100 * (value / group_total), digits = 2),
         group = "All") %>% 
  rename(edu_level = name,
         estimate = value) %>% 
  select(GEOID, locality, group, group_total, edu_level, estimate, percent, year)

alb_edu_attain_race <- read_csv("../data/alb_edu_attain_race_county_2022.csv") %>% 
  select(-group_total_moe) %>% 
  rename(group = race)

alb_edu_attain_all <- rbind(alb_edu_attain, alb_edu_attain_race)

alb_edu_attain_race_plot <- alb_edu_attain_all %>% 
  filter(group_total != 0) %>% 
  filter(group != "White") %>% 
  mutate(label = factor(edu_level, 
                        levels = c("less_than_hs", 
                                   "hs_only", 
                                   "bachelors_up"), 
                        labels = c("Less than a HS diploma", "High School diploma, no college", "Bachelor's degree or higher")),
         group = factor(group,
                       levels = c("All", "Amer_Indian", "Asian", "Black", "Hispanic", "Multi", "NHPI", "Other", "White_non_hisp"),
                       labels = c("All Over 25 years", "American Indian", "Asian", "Black", "Hispanic", "Multiracial", "Native Hawaiian/Pacific Islander", "Other Racial Identities", "White")),
         text = case_when(percent >= 1 ~ paste0(round(percent, 0), "%"),
                          percent < 1 ~ "")
  )

# Stacked bar
alb_edu_race_plot <- alb_edu_attain_race_plot %>% 
  filter(!group %in% c("Other Racial Identities")) %>% 
  filter(group_total >= 400) %>% 
  ggplot(aes(x = group, y = percent, group = group, fill = label, 
             label = text)) +
  geom_bar(stat = "identity", color = "white") + 
  geom_text(size = 3, position = position_stack(vjust = 0.5)) +
  scale_fill_manual(values = c("#3B8EA5", "#8C96C6", "#FFA679")) +
  # scale_fill_manual(values = c("#FEF6B5", "#FFA679", "#E15383")) +
  scale_x_discrete(name = "") +
  scale_y_continuous(labels = label_percent(scale = 1),
                     name = "") +
  labs(title = "Educational Attainment by Race/Ethnicity (25 Years and Over)",
       subtitle = locality_name, 
       caption = source_acs) +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "top",
        panel.grid.major.x = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title.position= "plot",
        plot.caption.position = "plot")

alb_edu_race_plot

```

```{r, echo=FALSE, fig.height=9, fig.width=11}
# Educational Attainment, with BA's by tract, Albemarle, 2022 ----
alb_edu_attain_tract <- read_csv("../data/alb_edu_attain_tract_2022.csv") %>%
  mutate(GEOID = as.character(GEOID),
         percent = round(percent, 0))

alb_edu_attain_tract <- alb_edu_attain_tract %>%
  left_join(alb_geo, by = "GEOID") %>% 
  st_as_sf()

alb_attain_BAs <- alb_edu_attain_tract %>%
  filter(label == "Bachelor's degree or higher")

# Geospatial visualization
alb_educ_attain_map <- alb_attain_BAs %>% 
  mutate(text = paste0(percent, "%")) %>% 
  ggplot() +
  annotation_map_tile(zoomin = 1, progress = "none", cachedir = "../data/tempdata/") +
  geom_sf(aes(fill = percent), color = "white") +
  geom_sf_text(aes(label = text), size = 2.5, color = "black") +
  scale_fill_stepsn(colors = pal_edu,
                    labels = scales::label_percent(scale = 1),
                      n.breaks = 6,
                    guide = guide_colourbar(title = "Percent BA or Higher",
                                            title.position = "top",
                                            direction = "horizontal",
                                            title.hjust = 0.5 ,
                                            # nbin = 6,
                                            theme = theme(legend.key.height  = unit(0.5, "lines"),
                                                          legend.key.width = unit(12, "lines"),
                                                          # legend.key.width  = unit(1, "lines"),
                                                          # legend.key.height = unit(10, "lines"),
                                                          text = element_text(size = 11,
                                                                              # face = "bold",
                                                                              # colour = "gray40"
                                                                              )) )
                    )+
  # labs(title = "Education Level: Bachelor's Degree or Higher", 
  #     subtitle = locality_name, 
  #     caption = source_acs) +
  theme_map()+
  theme(legend.position.inside=c(1, 1.04),
        legend.justification="right",
        # legend.position="right",
        # legend.justification = "center",
        plot.title = element_text(size = 14),
        plot.subtitle = element_text(size = 14)
        )

# Rank plot
alb_BA_data <- alb_attain_BAs %>%
  group_by(percent) %>% 
  summarise(tractnames = paste(tractnames, collapse = "; ")) %>% 
  na.exclude() 

names <- alb_BA_data$tractnames
BA_attain <- alb_BA_data$percent

alb_educ_attain_rank <- ggplot(alb_BA_data, aes(x = 0, y = percent, label = names)) +
    geom_line(color = "grey", size = 1)+
    geom_point(aes(color=as.factor(percent)), size=5)+
    geom_text(label = str_wrap(names, width = 50), hjust = 0, nudge_x = 0.006, 
              nudge_y = 0.03,
              size = 3.5,
              lineheight = 0.8) +
   scale_color_carto_d(name = "Percent BA or Higher: ",
                           type = "diverging", palette = "PinkYl", direction = 1) +
    scale_x_continuous(limits = c(0,.1),
                       expand = c(0.03, 0.003))+
    scale_y_continuous(
                       breaks = BA_attain,
                       labels = paste0(BA_attain, "%")
                       ) +
  theme_minimal()+
    theme(axis.line.x = element_blank(),
          axis.ticks.x = element_blank(),
          axis.text.x = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          panel.grid.minor = element_blank(),
          panel.grid.major = element_blank(),
          axis.text.y = element_text(size = 11),
          axis.ticks = element_line(linewidth = .5),
          axis.ticks.length.y = unit(.25, "cm"),
          plot.title.position= "plot",
          plot.caption.position = "plot",
          plot.caption = element_text(hjust = 0),
          legend.position="none")
  
  (alb_educ_attain_map + patchwork::free(alb_educ_attain_rank)) +
  plot_layout(widths = c(1.75, 1)) +
  plot_annotation(title = "Education Level: Bachelor's Degree or Higher", 
      subtitle = locality_name, 
      caption = source_acs)


```

```{r, echo=FALSE}
# Advanced Courses, AP & Dual Enrollment: Albemarle ----

alb_adv_enroll <- read_csv("../data/alb_adv_enroll_2022_2023.csv")  

# AP & Dual Enrollment
alb_adv_enroll %>% 
  filter(! label %in% c("American Indian or Alaska Native", "Native Hawaiian or Pacific Islander")) %>% 
  select(label, ap_percent, dual_percent) %>% 
  pivot_longer(ap_percent:dual_percent, names_to = "type") %>% 
  mutate(label = factor(label,
                        levels = c("All Students", "Economically Disadvantaged",
                                   "Asian", "Black, not of Hispanic origin", "Hispanic",
                                   "Non-Hispanic, two or more races", "White, not of Hispanic origin"),
                        labels = c("All Students", "Economically \nDisadvantaged",
                                   "Asian", "Black", "Hispanic",
                                   "Multiracial", "White")),
         type = factor(type,
                       levels = c("ap_percent", "dual_percent"),
                       labels= c("Students taking 1 or more AP Courses", "Students taking 1 or more Dual Enrollment Courses")),
         value = round(value, 0),
         text = paste0(value, "%")) %>% 
  ggplot(aes(x = label, y = value, fill = type)) +
  geom_bar(stat = "identity", position = position_dodge2(width = 0.9, preserve = "single"), width = 0.8) + 
  geom_text(aes(label = text), 
              position = position_dodge2(width = 0.9, preserve = "single"), 
              vjust = -1,
              # hjust = -0.2,
              size = 3) +
  scale_x_discrete(name = "") +
  scale_y_continuous(labels = label_percent(scale = 1),
                     limits = c(0,100),
                     name = "") +
  scale_fill_manual(values = c("#3B8EA5", "#8C96C6")) +
  labs(title = "AP & Dual Enrollment",
       subtitle = school_district, 
       caption = source_vdoe) +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "top",
        panel.grid.major.x = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title.position= "plot",
        plot.caption.position = "plot")

# Short Term Suspensions: Albemarle ----
alb_suspensions <- read_csv("../data/alb_st_suspensions_2022_2023.csv")  

alb_suspensions %>% 
  filter(! subgroup %in% c("American Indian", "Native Hawaiian")) %>% 
  select(subgroup, percent_of_the_student_population, percent_of_short_term_suspensions) %>% 
  pivot_longer(percent_of_the_student_population:percent_of_short_term_suspensions, names_to = "type") %>% 
  mutate(subgroup = factor(subgroup,
                        levels = c("White", "Multiple Races", "Hispanic", "Black", "Asian")),
         type = factor(type,
                       levels = c("percent_of_the_student_population", "percent_of_short_term_suspensions"),
                       labels= c("Percent of the student population", "Percent of short term suspensions")),
         value = round(value, 0),
         text = paste0(value, "%")) %>% 
  ggplot(aes(x = subgroup, y = value, fill = type)) +  
  geom_bar(stat = "identity", position = position_dodge2(width = 0.9, preserve = "single"), width = 0.8) +
  geom_text(aes(label = text), 
            position = position_dodge2(width = 0.9, preserve = "single"), 
            vjust = 0.5,
            hjust = -0.2,
            size = 3) +
  scale_x_discrete(name = "") +
  scale_y_continuous(labels = scales::percent_format(scale = 1),
                     limits = c(0,100),
                     expand = expansion(mult = c(0, 0)),
                     name = "") +
  scale_fill_manual(values = c("#b2b8be", "#ff641e")) + 
  coord_flip() +
  theme_minimal() +
  theme(legend.position = "top",
        panel.grid.minor.x = element_blank(),
        plot.title.position= "plot",
        plot.caption.position = "plot") +
  guides(fill = guide_legend(reverse = TRUE)) +
  labs(fill = "", 
       title = "Short Term Suspension Incidents by Race/Ethnicity",
       subtitle = school_district, 
       caption = source_vdoe)

```

```{r, echo=FALSE, fig.width=9}
# Chronic Absenteeism: Albemarle ----
alb_absent <- read_csv("../data/alb_absenteeism_2022_2023.csv")  

alb_absent %>% 
  filter(! subgroup %in% c("American Indian", "Native Hawaiian")) %>% 
  mutate(subgroup = factor(subgroup,
                        levels = c("All Students", "Economically Disadvantaged", "Students with Disabilities",
                                   "Male", "Female",
                                   "Asian", "Black", "Hispanic", "Multiple Races", "White"),
                        labels = c("All Students", "Economically \nDisadvantaged", "Students with \nDisabilities",
                                   "Male", "Female",
                                   "Asian", "Black", "Hispanic", "Multiracial", "White")),
         percent_above_10 = round(percent_above_10, 0),
         text = paste0(percent_above_10, "%")) %>% 
  ggplot(aes(x = subgroup, y = percent_above_10, fill = subgroup)) +
  geom_bar(stat = "identity", width = 0.8) + 
  geom_text(aes(label = text), 
            vjust = -1,
            size = 3,
            color = "black") +
  scale_x_discrete(name = "") +
  scale_y_continuous(labels = label_percent(scale = 1),
                     limits = c(0,60),
                     name = "") +
  scale_fill_manual(values = c("#b2b8be", rep("#3B8EA5",9)))+
  labs(title = "Chronic Absenteeism",
       subtitle = school_district, 
       caption = source_vdoe) +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "none",
        panel.grid.major.x = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title.position= "plot",
        plot.caption.position = "plot")



```

