---
title: "Equity Profile Living Standards - Albemarle"
output: html_document
---

```{css, echo=FALSE}
.main-container.container-fluid {
max-width: 1200px;
  margin-left: auto;
  margin-right: auto;
  padding: 0 4.167%;
}

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# Load packages ----
library(tidyverse)
library(scales)
library(RColorBrewer)
library(ggspatial)
library(tigris)
library(readxl)
library(stringr)
library(sf)
library(ggthemes)
library(rcartocolor)
library(patchwork)

# Education palette ----
pal_inc <- carto_pal(7, "Emrld")
# "#D3F2A3" "#97E196" "#6CC08B" "#4C9B82" "#217A79" "#105965" "#074050"


# Tract geometries ----
alb_geo <- tracts(state = "VA", county = "003")

# Common Items
locality_name <- "Albemarle County"
source_acs <- "Data Source: U.S. Census Bureau, American Community Survey, 2022"

```

```{r, echo=FALSE, fig.height=5}
# Median personal earnings, by sex and race: Albemarle, 2022 ----
alb_med_earnings_race_county <- read_csv("../data/alb_med_earnings_race_county_2022.csv") %>%
  mutate(estimate = round(estimate, -2))

alb_med_earnings_race_county %>% 
  filter(race != "White") %>% 
  mutate(race = factor(race, levels = c("White, Not Hispanic or Latino", "Mutiracial", "Hispanic or Latino", "Black", "Asian"),
                       labels = c("White", "Mutiracial", "Hispanic", "Black", "Asian")),
         text = paste0("$", prettyNum(estimate, big.mark=",", preserve.width="none"))) %>%
  ggplot(aes(x = race, y = estimate, fill = sex)) +  
  geom_bar(stat = "identity", position = position_dodge2(width = 0.9, preserve = "single"), width = 0.8) +
  geom_text(aes(label = text), 
            position = position_dodge2(width = 0.9, preserve = "single"), 
            # vjust = 0.5,
            hjust = -0.15,
            size = 3) +
  scale_x_discrete(expand = expansion(mult = c(0, 0)),
                   name = "") +
  scale_y_continuous(labels = scales::label_currency(scale = 1, scale_cut = cut_short_scale()),
                     limits = c(0,70000),
                     expand = expansion(mult = c(0, 0)),
                     name = "") +
  scale_fill_manual(values = c("#b2b8be","#3B8EA5", "#6CC08B")) + 
  coord_flip() +
  theme_minimal() +
  theme(legend.position = "top",
        panel.grid.minor.x = element_blank()) +
  guides(fill = guide_legend(reverse = TRUE)) +
  labs(fill = "",
       title = "Median Personal Earnings by Sex and Race", 
      subtitle = locality_name, 
      caption = source_acs) 


```


```{r, echo=FALSE, fig.width=12, fig.height=12}
# Median household income by tract: Albemarle, 2022 ----
alb_med_hhinc_tract <- read_csv("../data/alb_med_hhinc_tract_2022.csv") %>%
  mutate(GEOID = as.character(GEOID),
         estimate = round(estimate, -3))

alb_med_hhinc_tract <- alb_med_hhinc_tract %>%
  left_join(alb_geo, by = "GEOID") %>% 
  st_as_sf()

# Geospatial visualization
alb_inc_map <- alb_med_hhinc_tract %>%
  filter(group == "All Households") %>%
  mutate(text = paste0("$", prettyNum((estimate/1000), big.mark=",", preserve.width="none"), "K")
         ) %>%
  ggplot() +
  annotation_map_tile(zoomin = 1, progress = "none", cachedir = "../data/tempdata/") +
  geom_sf(aes(fill = estimate), color = "white") +
  geom_sf_text(aes(label = text), size = 2.5, color = "black") +
  scale_fill_stepsn(colors = pal_inc,
                    labels = scales::label_currency(scale = .001, suffix = "K"),
                    # labels = scales::label_currency(scale = 1),
                    n.breaks = 6,
                    guide = guide_colourbar(title = "Median Household Income",
                                            title.position = "top",
                                            direction = "horizontal",
                                            title.hjust = 0.5,
                                            # nbin = 6,
                                            theme = theme(legend.key.height  = unit(0.5, "lines"),
                                                          legend.key.width = unit(20, "lines"),
                                                          text = element_text(size = 11)) 
                                            )
                    )+
  # labs(title = "Median Household Income", 
  #     subtitle = locality_name, 
  #     caption = source_acs) +
  theme_map()+
  theme(legend.position.inside=c(1, 1.04),
        legend.justification="right",
        plot.title = element_text(size = 14),
        plot.subtitle = element_text(size = 14))

# Rank plot
alb_inc_data <- alb_med_hhinc_tract %>% 
  filter(group == "All Households") %>%
  group_by(estimate) %>% 
  summarise(tractnames = paste(tractnames, collapse = "; ")) %>% 
  na.exclude() 

names <- alb_inc_data$tractnames
estimate_label <- alb_inc_data$estimate

alb_inc_rank <- ggplot(alb_inc_data, aes(x = 0, y = estimate, label = names)) +
    geom_line(color = "grey", size = 1)+
    geom_point(aes(color=as.factor(estimate)), size=5)+
    geom_text(label = names, hjust = 0, nudge_x = 0.006, 
              nudge_y = 0.03,
              size = 3.5,
              lineheight = 0.8) +
   scale_color_carto_d(name = "Median Household Income: ",
                           type = "diverging", palette = "Emrld", direction = 1) +
    scale_x_continuous(limits = c(0,.1),
                       expand = c(0.03, 0.003))+
    scale_y_continuous(
                       breaks = estimate_label,
                       labels = scales::label_currency(scale = .001, suffix = "K")
                       # labels = paste0("$",prettyNum(estimate_label, big.mark=",", preserve.width="none")
                                       # )
                       ) +
  theme_minimal()+
    theme(axis.line.x = element_blank(),
          axis.ticks.x = element_blank(),
          axis.text.x = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          panel.grid.minor = element_blank(),
          panel.grid.major = element_blank(),
          axis.text.y = element_text(size = 11),
          axis.ticks = element_line(linewidth = .5),
          axis.ticks.length.y = unit(.25, "cm"),
          plot.title.position= "plot",
          plot.caption.position = "plot",
          plot.caption = element_text(hjust = 0),
          legend.position="none")
  
  (alb_inc_map + patchwork::free(alb_inc_rank)) +
  plot_layout(widths = c(2, 1)) +
  plot_annotation(title = "Median Household Income by Tract", 
      subtitle = locality_name, 
      caption = source_acs)

```

```{r, echo=FALSE, fig.height=4}
# Median household income by Race: Albemarle, 2022 ----
alb_med_hhinc_county <- read_csv("../data/alb_med_hhinc_county_2022.csv") %>%
  mutate(estimate = round(estimate, -2))

alb_med_hhinc_county %>%
  filter(!group %in% c("White", "American Indian and Alaska Native", "NHPI", "Other")) %>% 
  mutate(group = factor(group, levels = c("White, Not Hispanic or Latino", "Multiracial", "Hispanic or Latino", "Black", "Asian", "All Households"),
                       labels = c("White", "Multiracial", "Hispanic", "Black", "Asian", "All Households")),
         text = paste0("$", prettyNum(estimate, big.mark=",", preserve.width="none"))) %>%
  ggplot(aes(x = group, y = estimate, fill = group)) +
  coord_flip() +
  geom_bar(stat = "identity", width = 0.7) +
  geom_text(aes(label = text), 
            vjust = 0.5,
            hjust = -0.2,
            size = 3,
            color = "black") +
  scale_y_continuous(labels = scales::label_currency(scale = 1, scale_cut = cut_short_scale()),
                     breaks = c(0, 25000, 50000, 75000, 100000, 125000, 150000),
                     limits = c(0,150000),
                     expand = expansion(mult = c(0, .1))) +
  scale_fill_manual(values = c(rep("#6CC08B",5),"#b2b8be"))+
  labs(
    x = "",
    y = "Median Household Income",
    title = "Median Household Income by Race",
    subtitle = locality_name, 
    caption = source_acs
  ) +
  theme_minimal() +
  theme(legend.position = "none",
        panel.grid.minor.x = element_blank())

```

```{r, echo=FALSE}
# ALICE thresholds: Albemarle, 2010-2022 ----
alb_ALICE_threshold <- read_csv("../data/alb_ALICE_threshold_2010_2022.csv")

alb_ALICE_threshold %>% 
  pivot_longer(alice_threshold_hh_under_65:alice_threshold_hh_65_years_and_over, names_to = "level", values_to = "threshold") %>% 
  mutate(pos = case_when(level == "alice_threshold_hh_under_65" ~ 1,
                         level == "alice_threshold_hh_65_years_and_over" ~ -1
                         ),
         text = paste0("$", prettyNum(round(threshold,0), big.mark=",", preserve.width="none"))) %>% 
  ggplot(aes(x = year, y = threshold, color = level, label = text)) +
  geom_line(linewidth = 1) +
  geom_point() +
  geom_text(aes(y = (threshold + sign(pos)*6000)), size = 3, show.legend = FALSE, color = "black") +
  scale_x_continuous(
    breaks = seq(from = 2010, to = 2022, by = 1),
                     name = "") +
  scale_y_continuous(labels = label_currency(scale = 1, scale_cut = cut_short_scale()),
                     breaks = c(0, 20000, 40000, 60000, 80000, 100000),
                     limits = c(0,100000),
                     name = "") +
    scale_color_manual(values = c("#b2b8be", "#3B8EA5")) +
    guides(color = guide_legend(reverse = TRUE)) +
labs(color = "", 
       title = "ALICE Thresholds 2010-2022", 
      subtitle = locality_name, 
      caption = "Data Sources: ALICE Threshold, 2010–2022; U.S. Census Bureau, American Community Survey, 2010–2022") +  
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "top",
        axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid.minor = element_blank())


# ALICE households by race/ethnicity: Albemarle, 2022 ----
alb_ALICE_households_by_race <- read_csv("../data/alb_ALICE_households_by_race_2022.csv")

alb_ALICE_households_by_race <- alb_ALICE_households_by_race %>% 
  mutate(level = case_when(level == "above_alice_households" ~ "above",
                           level == "alice_households" ~ "alice",
                           level == "poverty_households" ~ "poverty",
                           .default = level))

alb_ALICE_households_by_race <- alb_ALICE_households_by_race[order(alb_ALICE_households_by_race$level),]

alb_ALICE_households_by_race %>% 
  arrange(desc(level)) %>% 
  mutate(group = factor(group,
                       levels = c("Asian", "Black", "Hispanic", "2+ Races", "White", "All"),
                       labels = c("Asian", "Black", "Hispanic", "Multiracial", "White", "All Households")),
  text = case_when(percent >= 1 ~ paste0(round(percent, 0), "%"),
                   percent < 1 ~ paste0(round(percent, 1), "%"))) %>%
  ggplot(aes(x = group, y = percent, group = group, fill = level, 
             label = text)) +
  geom_bar(stat = "identity", color = "white") + 
  geom_text(size = 3, position = position_stack(vjust = 0.5)) +
  scale_fill_manual(values = c("#b2b8be", "#3B8EA5", "#97E196")) +
  scale_x_discrete(name = "") +
  scale_y_continuous(labels = label_percent(scale = 1),
                     name = "") +
  guides(fill = guide_legend(reverse = TRUE)) +
  labs(color = "", 
       title = "ALICE Households by Race/Ethnicity", 
      subtitle = locality_name, 
      caption = "Data Sources: ALICE Threshold, 2022; U.S. Census Bureau, American Community Survey, 2022") +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "top",
        panel.grid.major.x = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.minor = element_blank())



```

```{r, echo=FALSE, fig.height=9, fig.width=8.5}
# Rent Burdened Households: Albemarle, 2022 ----

alb_rent_burden_county <- read_csv("../data/alb_rent_burden_county_2022.csv")  
alb_rent_burden_tract <- read_csv("../data/alb_rent_burden_tract_2022.csv")  

alb_rent_burden_tract <- alb_rent_burden_tract %>% 
  mutate(label = paste0(level, "\n", rent_burden),
         text = case_when(percent >= 1 ~ paste0(round(percent, 0), "%"),
                   percent < 1 ~ ""),
         rentallabel = prettyNum(total_units, big.mark=",", preserve.width="none")
         # rentallabel = paste0("Total Units: ", as.character(alb_rent_burden_tract$total_units))
         )
alb_rent_burden_tract <- alb_rent_burden_tract[order(alb_rent_burden_tract$tractnames, decreasing=TRUE),]
rentallabel <- as.list(alb_rent_burden_tract$rentallabel) %>% unique()

unburdened_plot <- alb_rent_burden_tract %>% 
  filter(level %in% c("Not burdened")) %>% 
  ggplot(aes(y = tractnames, x = percent, fill = factor(label), label= text)) +  
  geom_bar(stat = "identity") +
  geom_text(position = position_stack(vjust = 0.3), 
            # vjust = 0.5,
            # hjust = 0.5,
            size = 3) +
  scale_y_discrete(position = "left",
                   limits=rev,
                   name = "") +
  scale_x_reverse(labels = scales::percent_format(scale = 1),
                     breaks = seq(from = 25, to = 100, by = 25),
                     limits = c(100,0),
                     expand = expansion(mult = c(0, 0)),
                     name = "") +
  scale_fill_manual(values = c("#b2b8be")) + 
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.justification="right",
        legend.position = c(0.65, 1.06),
        legend.direction = 'horizontal',
        panel.grid.minor.x = element_blank(),
        plot.margin = unit(c(0,0,0,0), "line"),
        axis.text = element_text(color = "black"))

total_burden <- alb_rent_burden_tract %>% 
  filter(level %in% c("Burdened", "Severely Burdened")) %>% 
  group_by(tractnames) %>% 
  summarise(total_burden_per = paste0(round(sum(percent), 0), "%"),
            rentallabel = first(rentallabel),
            burden_label = paste0(total_burden_per, " | ", as.character(rentallabel)))

total_burden <- total_burden[order(total_burden$tractnames, decreasing=TRUE),]
burden_label <- as.list(total_burden$burden_label)

burdened_plot <- alb_rent_burden_tract %>% 
  filter(level %in% c("Burdened", "Severely Burdened")) %>% 
  ggplot(aes(y = tractnames, x = percent, fill = factor(label), group = tractnames, label = text)) +  
  geom_bar(stat = "identity", color = "white") +
  geom_text(position = position_stack(vjust = 0.5),
            # vjust = 0.5,
            hjust = 0.001,
            size = 3) +
  scale_y_discrete(position = "right",
                   labels = burden_label,
                   limits=rev,
                   name = "Total Percent Burdened | Total Rental Units by Census Tract") +
  scale_x_continuous(labels = scales::percent_format(scale = 1),
                     breaks = seq(from = 25, to = 100, by = 25),
                     limits = c(0,100),
                     expand = expansion(mult = c(0.005, 0)),
                     name = "") +
  scale_fill_manual(values = c("#3B8EA5","#ff641e")) + 
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.justification="right",
        legend.position = c(1.1, 1.06),
        legend.direction = 'horizontal',
        panel.grid.minor.x = element_blank(),
        plot.margin = unit(c(3,0,0,0), "line"),
        axis.text = element_text(color = "black"),
        axis.text.y.right = element_text(margin = margin(0,0,0,-25)))


(unburdened_plot + burdened_plot) + 
  plot_annotation(title = 'Rent Burdened Households by Census Tract',
                  subtitle = locality_name,
                  caption = source_acs)
```

```{r, echo=FALSE, fig.height=10, fig.width=11}
# Home Ownership by tract: Albemarle, 2022 ----
alb_tenure_tract <- read_csv("../data/alb_tenure_tract_2022.csv") %>%
  mutate(GEOID = as.character(GEOID),
         percent = round(percent,0),
         text_color = case_when(percent >= 70 ~ "white",
                                percent <70 ~ "black"))

alb_tenure_tract <- alb_tenure_tract %>%
  left_join(alb_geo, by = "GEOID") %>% 
  st_as_sf()

# Geospatial visualization
alb_homeowner_map <- alb_tenure_tract %>%
  filter(label == "Owner occupied") %>%
  mutate(text = paste0(round(percent,0), "%")) %>%
  ggplot() +
  annotation_map_tile(zoomin = 1, progress = "none", cachedir = "../data/tempdata/") +
  geom_sf(aes(fill = percent), color = "white") +
  scale_fill_stepsn(colors = pal_inc,
                    labels = scales::label_percent(scale = 1),
                    n.breaks = 7,
                    guide = guide_colourbar(title = "Percent Home Ownership",
                                            title.position = "top",
                                            direction = "horizontal",
                                            title.hjust = 0.5,
                                            # nbin = 6,
                                            theme = theme(legend.key.height  = unit(0.5, "lines"),
                                                          legend.key.width = unit(18, "lines"),
                                                          text = element_text(size = 11)) 
                                            )
                    )+
  geom_sf_text(aes(label = text, color = text_color), size = 2.5, show.legend = FALSE) +
  scale_color_manual(values = c("black", "white")) +
  # labs(title = "Home Ownership by Tract", 
  #     subtitle = locality_name, 
  #     caption = source_acs) +
  theme_map()+
  theme(legend.position.inside=c(1, 1.06),
        legend.justification="right",
        plot.title = element_text(size = 14),
        plot.subtitle = element_text(size = 14))

# Rank plot
alb_tenure_data <- alb_tenure_tract %>% 
  filter(label == "Owner occupied") %>%
  group_by(percent) %>% 
  summarise(tractnames = paste(tractnames, collapse = "; ")) %>% 
  na.exclude() 

names <- alb_tenure_data$tractnames
homeowner <- alb_tenure_data$percent

alb_homeowner_rank <- ggplot(alb_tenure_data, aes(x = 0, y = percent, label = names)) +
    geom_line(color = "grey", size = 1)+
    geom_point(aes(color=as.factor(percent)), size=5)+
    geom_text(label = str_wrap(names, width = 50), hjust = 0, nudge_x = 0.006, 
              nudge_y = case_when(alb_tenure_data$percent %in% c(5,6) ~ 0.1,
                                  alb_tenure_data$percent %in% c(4) ~ -0.1,
                             .default = 0.05),
              size = 3.5,
              lineheight = 0.7) +
   scale_color_carto_d(name = "Percent Home Ownership: ",
                           type = "diverging", palette = "Emrld", direction = 1) +
    scale_x_continuous(limits = c(0,.1),
                       expand = c(0.03, 0.003))+
    scale_y_continuous(
                       breaks = homeowner,
                       labels = paste0(homeowner, "%")
                       ) +
  theme_minimal()+
    theme(axis.line.x = element_blank(),
          axis.ticks.x = element_blank(),
          axis.text.x = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          panel.grid.minor = element_blank(),
          panel.grid.major = element_blank(),
          axis.text.y = element_text(size = 11),
          axis.ticks = element_line(linewidth = .5),
          axis.ticks.length.y = unit(.25, "cm"),
          plot.title.position= "plot",
          plot.caption.position = "plot",
          plot.caption = element_text(hjust = 0),
          legend.position="none")
  
  (alb_homeowner_map + patchwork::free(alb_homeowner_rank)) +
  plot_layout(widths = c(2, 1)) +
  plot_annotation(title = "Home Ownership by Census Tract", 
      subtitle = locality_name,
      caption = source_acs)

```

```{r, echo=FALSE}
# Home Ownership by Race, Albemarle 2012 & 2022 ----
alb_tenure_race_county <- read_csv("../data/alb_tenure_race_county_2012_2022.csv")

alb_homeowner_race <- alb_tenure_race_county %>% 
  filter(label == "Owner occupied") %>% 
  filter(!group %in% c("White", "American Indian/Native Alaskan", "Native Hawaiian/Pacific Islander", "Other")) %>% 
  select(group, percent, year) %>% 
  pivot_wider(names_from = year, values_from = percent) %>% 
  mutate(difference = `2022` - `2012`) %>% 
  pivot_longer(`2022`:`2012`) %>% 
  mutate(year = as.numeric(name))

anno_list = as.list(alb_homeowner_race$difference) %>% unique()

alb_homeowner_race %>% 
  mutate(text = paste0(round(value, 0), "%"),
         group = factor(group, levels = c("Asian", "Black", "Hispanic or Latino", "Multiracial", "White, Not Hispanic or Latino"),
                        labels = c("Asian", "Black", "Hispanic", "Multiracial", "White"))) %>% 
  ggplot(aes(x = year, y = value, label = text)) +
  geom_line(linewidth = 1, color = "#3B8EA5") +
  geom_point(color = "#3B8EA5") +
  geom_text(size = 4, nudge_y = 15, color = "#3B8EA5", fontface = "bold") +
  # geom_text(data = annot_list, size = 4, nudge_y = -25, color = "#3B8EA5", fontface = "bold") +
  # annotate("text", x = 2017, y = 25, label = c("1", "2", "3", "4", "5"), color = "#3B8EA5", fontface = "bold") +
  scale_x_continuous(breaks = c(2012,2022),
                     expand = expansion(mult = c(0.1, .1)),
                     name = "") +
  scale_y_continuous(labels = scales::label_percent(scale = 1),
                     breaks = c(0,100),
                     limits = c(0,100),
                     name = "") + 
  facet_wrap(~group, scales = "free") +
  labs(color = "", 
       title = "Home Ownership by Race: 2012 & 2022", 
      subtitle = locality_name, 
      caption = "Data Source: U.S. Census Bureau, American Community Survey, 2012, 2022") +  
  theme_minimal() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        strip.text = element_text(size = 12))

```

```{r, echo=FALSE, fig.height=9, fig.width=10}
# Gross Rent by tract: Albemarle, 2022 ----
alb_gross_rent_tract <- read_csv("../data/alb_gross_rent_tract_2022.csv") %>%
  mutate(GEOID = as.character(GEOID),
         estimate = round(estimate, -2))

alb_gross_rent_tract <- alb_gross_rent_tract %>%
  left_join(alb_geo, by = "GEOID") %>% 
  st_as_sf()

# Geospatial visualization
alb_rent_map <- alb_gross_rent_tract %>%
  mutate(text = case_when(is.na(estimate) ~ "",
                          !is.na(estimate) ~ paste0("$", prettyNum((estimate/1000), big.mark=",", preserve.width="none"), "K"))) %>%
  ggplot() +
  annotation_map_tile(zoomin = 1, progress = "none", cachedir = "../data/tempdata/") +
  geom_sf(aes(fill = estimate), color = "white") +
  geom_sf_text(aes(label = text), size = 2.5, color = "black") +
  scale_fill_stepsn(colors = pal_inc,
                    labels = scales::label_currency(scale = .001, suffix = "K"),
                    n.breaks = 6,
                    guide = guide_colourbar(title = "Gross Rent",
                                            title.position = "top",
                                            direction = "horizontal",
                                            title.hjust = 0.5,
                                            # nbin = 6,
                                            theme = theme(legend.key.height  = unit(0.5, "lines"),
                                                          legend.key.width = unit(18, "lines"),
                                                          text = element_text(size = 11)) 
                                            )
                    )+
  # labs(title = "Gross Rent by Census Tract", 
  #     subtitle = locality_name, 
  #     caption = source_acs) +
  theme_map()+
  theme(legend.position.inside=c(1, 1.04),
        legend.justification="right",
        plot.title = element_text(size = 14),
        plot.subtitle = element_text(size = 14))

# Rank plot
alb_rent_data <- alb_gross_rent_tract %>%
  group_by(estimate) %>% 
  summarise(tractnames = paste(tractnames, collapse = "\n")) %>% 
  na.exclude() 

names <- alb_rent_data$tractnames
estimate_label <- alb_rent_data$estimate

alb_rent_rank <- ggplot(alb_rent_data, aes(x = 0, y = estimate, label = names)) +
    geom_line(color = "grey", size = 1)+
    geom_point(aes(color=as.factor(estimate)), size=5)+
    geom_text(label = names, hjust = 0, nudge_x = 0.006, 
              nudge_y = 0.03,
              size = 3.5,
              lineheight = 0.8) +
   scale_color_carto_d(name = "Gross Rent: ",
                           type = "diverging", palette = "Emrld", direction = 1) +
    scale_x_continuous(limits = c(0,.1),
                       expand = c(0.03, 0.003))+
    scale_y_continuous(
                       breaks = estimate_label,
                       labels = scales::label_currency(scale = .001, suffix = "K")
                       # labels = paste0("$",prettyNum(estimate_label, big.mark=",", preserve.width="none"))
                       ) +
  theme_minimal()+
    theme(axis.line.x = element_blank(),
          axis.ticks.x = element_blank(),
          axis.text.x = element_blank(),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          panel.grid.minor = element_blank(),
          panel.grid.major = element_blank(),
          axis.text.y = element_text(size = 11),
          axis.ticks = element_line(linewidth = .5),
          axis.ticks.length.y = unit(.25, "cm"),
          plot.title.position= "plot",
          plot.caption.position = "plot",
          plot.caption = element_text(hjust = 0),
          legend.position="none")
  
  (alb_rent_map + patchwork::free(alb_rent_rank)) +
  plot_layout(widths = c(2, 1)) +
  plot_annotation(title = "Gross Rent by Census Tract", 
      subtitle = locality_name, 
      caption = source_acs)
```
